# Generated by Django 2.2.5 on 2019-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AddField(
            model_name='data',
            name='is_3d',
            field=models.TextField(default=True, verbose_name='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='order_crtdate',
            field=models.CharField(max_length=20),
        ),
    ]
