# Generated by Django 2.2.5 on 2019-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191209_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_3d',
            field=models.TextField(),
        ),
    ]
